FROM node:latest

WORKDIR '/app'

RUN apt-get update -y && apt-get install -y wget libxss1 libindicator7 fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libgtk-3-0 libnspr4 libnss3 libx11-xcb1 libxtst6 lsb-release xdg-utils

# Chrome repository
RUN cd /tmp/
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN dpkg -i ./google-chrome*.deb
RUN rm ./google-chrome*.deb
RUN apt-get install -f

COPY package.json .

RUN npm install
RUN npm install -g @angular/cli

# add app
COPY . .

EXPOSE 4200

# start app
CMD ng serve --host 0.0.0.0